name: daily-cron
on:
  schedule:
    - cron: '5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call email digest API
        run: |
          curl --request GET \
          --url 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=226008&date=20-08-2021' \
 
